
__all__ = [
	'aboutMeView',
	'consentFormView',
	'createAcctView',
	'currentHealthView',
	'fitLvlView',
	'forgotPwView',
	'fullHealthView',
	'homeView',
	'myelDiagView',
	'myelomaGeneticsView',
	'myelomaLabsView',
	'myLabsAddFacilityView',
	'myLabsFacilitiesView',
	'settingsView',
	'surveysView',
	'treatmentOptionsView',
	'treatmentsOutcomesView',
]